language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - DJANGO=1.7.11
    - DJANGO=1.8.7
    - DJANGO=1.9
    - DJANGO=1.10

matrix:
    exclude:
    - python: "3.5"  # django 1.7 does not support python 3.5
      env: DJANGO=1.7.11

install:
    - pip install argparse
    - pip install coverage
    - pip install codecov
    - pip install -q Django==$DJANGO
    - pip install -q -r requirements.txt

script: 
    - coverage run --source='.' quicktest.py helpdesk

after_success:
    - codecov