language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.3.7
    - DJANGO=1.4.13
    - DJANGO=1.5.8
    - DJANGO=1.6.5
install:
    - pip install argparse --use-mirrors
    - pip install -q Django==$DJANGO --use-mirrors
script: python quicktest.py helpdesk
